const test=require("node:test");const assert=require("node:assert/strict");const fs=require("fs");const os=require("os");const path=require("path");
const {openDatabase}=require("../db/connection");const{migrate}=require("../db/migrationRunner");const{createRepositories}=require("../repositories");const{createSqliteScheduledPostRunner}=require("./sqliteScheduledPostRunner");const{createChangeJournal}=require("../repositories/changeJournal");const{reverseExport,verifyReverse}=require("../migration/reverseMapper");const{onlineBackup,restoreBackup}=require("../db/backup");
const NOW="2026-10-05T00:00:00.000Z";const keyring={currentVersion:1,keys:new Map([[1,Buffer.alloc(32,7)]])};
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"phase3-")),file=path.join(dir,"db.sqlite3"),db=openDatabase(file);migrate(db,{now:()=>NOW});db.prepare(`INSERT INTO customers(id,slug,primary_email,status,plan,stripe_customer_id,created_at,updated_at)VALUES('c1','slug','a@example.test','trial','basic','cus_test',?,?)`).run(NOW,NOW);db.prepare(`INSERT INTO users(id,customer_id,email,role,is_owner,created_at,updated_at)VALUES('u1','c1','a@example.test','管理者',1,?,?)`).run(NOW,NOW);return{db,file,dir,close(){db.close();fs.rmSync(dir,{recursive:true,force:true});}};}
function addPost(f,id="p1",platform="x",containsUrl=false){const repos=createRepositories(f.db,{keyring,now:()=>NOW});repos.scheduledPosts.createWithJob({id,customerId:"c1",createdByUserId:"u1",platform,content:"hello",scheduledAt:NOW,containsUrl});return repos;}
function handlers(calls){return{posting_log:()=>({}),trial_post_count:()=>({externalReference:"n/a"}),stripe_meter:async x=>{calls.meter.push(x.idempotencyKey);return{};},email:async x=>{calls.email.push(x.idempotencyKey);return{};},notification:()=>({externalReference:"n/a"})};}
test("runner completes sent effects done without sending twice",async()=>{const f=fixture();try{addPost(f);const calls={sns:0,meter:[],email:[]};const runner=createSqliteScheduledPostRunner(f.db,{keyring,now:()=>NOW,postToPlatform:async()=>{calls.sns++;return{id:"external-1"};},effectHandlers:handlers(calls)});assert.equal((await runner.runOne()).state,"done");assert.equal(await runner.runOne(),null);assert.equal(calls.sns,1);assert.equal(calls.meter.length,1);assert.equal(calls.email.length,1);assert.equal(f.db.prepare("SELECT count(*) n FROM posting_logs").get().n,1);}finally{f.close();}});
test("two runners atomically claim and send once",async()=>{const f=fixture();try{addPost(f);let sends=0;const opts={keyring,now:()=>NOW,postToPlatform:async()=>{sends++;return{id:"one"};},effectHandlers:handlers({meter:[],email:[]})};const a=createSqliteScheduledPostRunner(f.db,{...opts,workerId:"a"}),b=createSqliteScheduledPostRunner(f.db,{...opts,workerId:"b"});await Promise.all([a.runOne(),b.runOne()]);assert.equal(sends,1);}finally{f.close();}});
test("request failure is ambiguous and never automatically retried",async()=>{const f=fixture();try{addPost(f);let sends=0;const r=createSqliteScheduledPostRunner(f.db,{keyring,now:()=>NOW,postToPlatform:async()=>{sends++;throw new Error("timeout");}});assert.equal((await r.runOne()).state,"ambiguous");assert.equal(await r.runOne(),null);assert.equal(sends,1);}finally{f.close();}});
test("explicit pre-send retry-safe error becomes failed",async()=>{const f=fixture();try{addPost(f);const r=createSqliteScheduledPostRunner(f.db,{keyring,now:()=>NOW,postToPlatform:async()=>{throw Object.assign(new Error("validation"),{retrySafe:true});}});assert.equal((await r.runOne()).state,"failed");}finally{f.close();}});
test("expired leases before and after request split pending and ambiguous",()=>{const f=fixture();try{const repos=addPost(f,"a");addPost(f,"b");const a=repos.jobs.claimNext({workerId:"w",dueAt:NOW,leaseExpiresAt:"2026-10-04T00:00:00Z"});const first=a.scheduled_post_id;const b=repos.jobs.claimNext({workerId:"w2",dueAt:NOW,leaseExpiresAt:"2026-10-04T00:00:00Z"});repos.jobs.markRequestStarted({scheduledPostId:b.scheduled_post_id,workerId:"w2",attemptId:b.current_attempt_id,at:NOW});const result=repos.jobs.recoverExpiredLeases({expiredBefore:NOW});assert.deepEqual(result,{ambiguous:1,retryable:1});assert.equal(repos.jobs.get(first).state,"pending");assert.equal(repos.jobs.get(b.scheduled_post_id).state,"ambiguous");}finally{f.close();}});
test("container id survives crash and is supplied on deliberate recovery",()=>{const f=fixture();try{const repos=addPost(f);const j=repos.jobs.claimNext({workerId:"w",dueAt:NOW,leaseExpiresAt:"2026-10-06T00:00:00Z"});repos.jobs.markRequestStarted({scheduledPostId:"p1",workerId:"w",attemptId:j.current_attempt_id});repos.jobs.recordExternalContainer({scheduledPostId:"p1",workerId:"w",attemptId:j.current_attempt_id,externalContainerId:"container-1"});assert.equal(repos.jobs.get("p1").external_container_id,"container-1");}finally{f.close();}});
test("local effect mutation and ledger completion rollback together",()=>{const f=fixture();try{const repos=addPost(f);repos.effects.ensure({scheduledPostId:"p1",effectType:"notification",idempotencyKey:"e"});const effect=repos.effects.listForPost("p1")[0];assert.throws(()=>repos.effects.runLocal(effect.id,{workerId:"w",leaseExpiresAt:"2099-01-01T00:00:00Z",at:NOW},()=>{f.db.prepare("UPDATE customers SET trial_post_count=1 WHERE id='c1'").run();throw new Error("crash");}));assert.equal(f.db.prepare("SELECT trial_post_count n FROM customers WHERE id='c1'").get().n,0);assert.equal(repos.effects.listForPost("p1")[0].state,"pending");}finally{f.close();}});
test("external effect crash becomes ambiguous on lease recovery",()=>{const f=fixture();try{const repos=addPost(f);repos.effects.ensure({scheduledPostId:"p1",effectType:"email",idempotencyKey:"mail"});const e=repos.effects.listForPost("p1")[0];repos.effects.claim({effectId:e.id,workerId:"w",leaseExpiresAt:"2026-10-04T00:00:00Z",at:NOW});assert.equal(repos.effects.recoverExpiredLeases({expiredBefore:NOW}).ambiguous,1);assert.equal(repos.effects.listForPost("p1")[0].state,"ambiguous");}finally{f.close();}});
test("change journal redacts secrets in same transaction",()=>{const f=fixture();try{createChangeJournal(f.db,{now:()=>NOW,uuid:()=>"tx"}).mutate({entityType:"customer",entityId:"c1",operation:"update",after:{accessToken:"secret",name:"ok"}},()=>f.db.prepare("UPDATE customers SET contact_name='ok' WHERE id='c1'").run());const row=f.db.prepare("SELECT * FROM change_journal WHERE transaction_id='tx'").get();assert.equal(row.transaction_id,"tx");assert.deepEqual(JSON.parse(row.after_json),{accessToken:"[REDACTED]",name:"ok"});}finally{f.close();}});
test("reverse mapper preserves endpoint counts and IDs",()=>{const f=fixture();try{addPost(f);const reverse=reverseExport(f.db,{keyring});const source={microcms:Object.fromEntries(Object.entries(reverse.microcms).map(([k,v])=>[k,JSON.parse(JSON.stringify(v))]))};const report=verifyReverse(source,reverse);assert.equal(report.countsAndIdsMatch,true);assert.equal(report.majorHashesMatch,true);}finally{f.close();}});
test("online backup and restore preserve integrity and counts",async()=>{const f=fixture();try{addPost(f);const backup=path.join(f.dir,"backup.sqlite3"),restored=path.join(f.dir,"restored.sqlite3");await onlineBackup(f.db,backup);const db2=restoreBackup(backup,restored);assert.equal(db2.prepare("PRAGMA integrity_check").pluck().get(),"ok");assert.equal(db2.prepare("SELECT count(*) FROM scheduled_posts").pluck().get(),1);db2.close();}finally{f.close();}});
test("data source defaults to microcms and invalid value never falls back",()=>{const{getDataSourceName}=require("../data/dataSource");assert.equal(getDataSourceName({}),"microcms");assert.throws(()=>getDataSourceName({SNS_POSTER_DATA_SOURCE:"typo"}),/Invalid/);});
test("Stripe webhook ledger suppresses completed duplicate",()=>{const f=fixture();try{const{createStripeWebhookRepository}=require("../repositories/stripeWebhookRepository");const repo=createStripeWebhookRepository(f.db,{now:()=>NOW});assert.ok(repo.begin({eventId:"evt-1",eventType:"invoice.paid"}));assert.equal(repo.finish("evt-1",{state:"done"}),true);assert.equal(repo.begin({eventId:"evt-1",eventType:"invoice.paid"}),null);}finally{f.close();}});
