const {shouldNotifyForScheduledPost}=require("./notificationPolicy");
function createSqliteScheduledPostEffects({db,repositories,customerStore,scheduleStore,sendScheduleResultEmail,sendOneShotPostResultEmail,reportMeterEvent,logger}){
 const repos=()=>typeof repositories==="function"?repositories():repositories;
 return{
  posting_log:()=>({}),
  trial_post_count:({scheduledPostId})=>{const post=db.prepare("SELECT * FROM scheduled_posts WHERE id=?").get(scheduledPostId);if(!post.source_schedule_id)return{externalReference:"not-applicable"};db.prepare("UPDATE customers SET trial_post_count=trial_post_count+1,updated_at=?,version=version+1 WHERE id=? AND status='trial'").run(new Date().toISOString(),post.customer_id);return{};},
  stripe_meter:async({scheduledPostId})=>{const customer=db.prepare("SELECT stripe_customer_id FROM customers WHERE id=(SELECT customer_id FROM scheduled_posts WHERE id=?)").get(scheduledPostId);for(const event of db.prepare("SELECT * FROM billing_meter_events WHERE scheduled_post_id=? AND state IN ('pending','failed')").all(scheduledPostId)){const claimed=repos().meterEvents.claim({id:event.id,workerId:"scheduled-effect",leaseExpiresAt:new Date(Date.now()+120000).toISOString()});if(!claimed)continue;try{await reportMeterEvent(event.event_name,customer.stripe_customer_id,event.idempotency_key);repos().meterEvents.finish(event.id,{state:"done",stripeEventIdentifier:event.idempotency_key});}catch(error){repos().meterEvents.finish(event.id,{state:"ambiguous",error:String(error.message||error)});throw error;}}return{};},
  email:async({scheduledPostId})=>{const post=db.prepare(`SELECT p.*,s.notify_email schedule_notify_email FROM scheduled_posts p LEFT JOIN schedules s ON s.id=p.source_schedule_id WHERE p.id=?`).get(scheduledPostId);if(!shouldNotifyForScheduledPost(post))return{externalReference:"disabled-by-policy"};const customer=await customerStore.getCustomerById(post.customer_id),shaped={...post,created_by:post.created_by_user_id,source_schedule_id:post.source_schedule_id};const ok=post.source_schedule_id?await sendScheduleResultEmail({schedule:await scheduleStore.getScheduleById(post.source_schedule_id),customer,post:shaped,platform:post.platform,success:true,logger}):await sendOneShotPostResultEmail({customer,recipientUserId:post.created_by_user_id,content:post.content,platform:post.platform,success:true,logger});if(!ok)throw Object.assign(new Error("email result was not confirmed"),{retrySafe:false});return{};},
  notification:()=>({externalReference:"not-required-on-success"}),
 };
}
module.exports={createSqliteScheduledPostEffects};
