const assert=require("node:assert/strict");const crypto=require("node:crypto");const fs=require("node:fs");const os=require("node:os");const path=require("node:path");const test=require("node:test");
const {openDatabase}=require("../db/connection");const {migrate}=require("../db/migrationRunner");const {contentHash,sha256}=require("./canonicalJson");
const {createRepositories}=require("../repositories");
const {exportSources}=require("./exportSources");const {loadExport,inspectExport}=require("./inspectExport");const {createShadowImporter}=require("./shadowImporter");const {verifyShadow}=require("./verifyShadow");
const NOW="2026-10-05T00:00:00.000Z";const keyring=()=>({currentVersion:1,keys:new Map([[1,crypto.randomBytes(32)]])});
function sources(){const customer={id:"c1",slug:"s1",email:"a@example.test",companyName:"",contactName:"A",status:["active"],plan:["Basic"],isVerified:true,
  users:[{fieldId:"users",userId:"u1",email:"a@example.test",passwordHash:"hash",role:["管理者"],sessionVersion:1}],createdAt:NOW,updatedAt:NOW};
 const schedule={id:"s1",customer_code:"c1",created_by:"u1",name:"test",platforms:["x"],url_mode:false,notify_email:true,start_date:"2026-10-01",weekdays:["mon"],daily_post_count:1,slot1_start:"09:00",slot1_end:"10:00",is_paused:false,auto_paused:false,round_robin_index:0,createdAt:NOW,updatedAt:NOW};
 const text={id:"t1",schedule_id:"s1",created_by:"u1",x_text:"hello",linkedin_text:"",approval_status:["none"],createdAt:NOW,updatedAt:NOW};
 const post={id:"p1",customer_code:"c1",created_by:"u1",source_schedule_id:"s1",platform:["x"],content:"hello",scheduled_at:NOW,status:["done"],contains_url:false,approval_status:[],createdAt:NOW,updatedAt:NOW};
 const log={id:"l1",customer_code:"c1",created_by:"u1",platform:["x"],content:"hello",platform_post_id:"external",posted_at:NOW,billing_period:"2026-10",meter_event_sent:true,contains_url:false,account_name:"account",createdAt:NOW,updatedAt:NOW};
 return {customers:[customer],post_schedules:[schedule],schedule_texts:[text],scheduled_posts:[post],posting_logs:[log]};}
function bundle(overrides={}){const microcms={...sources(),...(overrides.microcms||{})};const json={"client_tokens.json":{"c1":{x:{user_id:"x1",username:"name",access_token:"secret",updated_at:NOW}}},
  "sns_history.json":{"x:x1":{firstCustomerId:"c1",firstConnectedAt:NOW}},"scheduled_post_retries.json":{},"posting_log_origins.json":{"l1":{scheduledPostId:"p1"}},
  "announcements.json":[],"announcement_reads.json":{},"x_surcharge_current.json":null,"x_surcharge_reservation.json":null,"admin_stats_last_month.json":{},"admin_stats_this_month.json":{},...(overrides.json||{})};
 const manifest={version:1,exportedAt:NOW,microcms:{},json:{}};for(const [name,rows] of Object.entries(microcms))manifest.microcms[name]={count:rows.length};
 manifest.manifestHash=contentHash({microcms,json,nonce:overrides.nonce||"a"});return {manifest,microcms,json};}
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"phase2-"));const db=openDatabase(path.join(dir,"db.sqlite3"));migrate(db);return{dir,db,close(){db.close();fs.rmSync(dir,{recursive:true,force:true})}};}
test("exporter uses GET pagination and writes manifest hashes without leaking records",async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"export-"));const jsonDir=path.join(dir,"json");const out=path.join(dir,"out");fs.mkdirSync(jsonDir);for(const n of ["client_tokens.json","sns_history.json","scheduled_post_retries.json","posting_log_origins.json","announcements.json","announcement_reads.json","x_surcharge_current.json","admin_stats_last_month.json","admin_stats_this_month.json"])fs.writeFileSync(path.join(jsonDir,n),n==="announcements.json"?"[]":"{}");
 const data=sources();const methods=[];const fake=async(url,opt)=>{methods.push(opt.method);const endpoint=url.match(/api\/v1\/([^?]+)/)[1];return{ok:true,json:async()=>({contents:data[endpoint]})}};
 try{const manifest=await exportSources({outputDirectory:out,jsonDirectory:jsonDir,serviceDomain:"fixture",apiKey:"hidden",fetchImpl:fake,now:()=>NOW});assert.ok(methods.every((m)=>m==="GET"));assert.equal(manifest.microcms.customers.count,1);assert.equal(manifest.microcms.customers.contentHash,contentHash(data.customers));assert.equal(fs.statSync(path.join(out,"customers.json")).mode&0o777,0o600);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test("inspector reports duplicate, orphan, unknown and schema differences",()=>{const b=bundle();b.microcms.customers.push({...b.microcms.customers[0]});b.microcms.scheduled_posts[0].platform=["unknown"];const q=inspectExport(b);assert.ok(q.issues.some((i)=>i.code==="duplicate_source_id"));assert.ok(q.issues.some((i)=>i.code==="unknown_platform"));});
test("import normalizes relations, variants, jobs, origins and encrypts token",()=>{const f=fixture();try{const ring=keyring();const b=bundle();const result=createShadowImporter(f.db,{keyring:ring,now:()=>NOW}).importBundle(b);assert.equal(result.rerun,false);assert.equal(f.db.prepare("SELECT count(*) n FROM users").get().n,1);assert.equal(f.db.prepare("SELECT count(*) n FROM schedule_text_variants").get().n,1);assert.equal(f.db.prepare("SELECT state FROM scheduled_post_jobs").get().state,"done");assert.equal(f.db.prepare("SELECT scheduled_post_id FROM posting_logs").get().scheduled_post_id,"p1");const token=f.db.prepare("SELECT access_token_ciphertext value FROM social_accounts").get().value;assert.ok(!token.includes("secret"));}finally{f.close()}});
test("identical import is idempotent",()=>{const f=fixture();try{const importer=createShadowImporter(f.db,{keyring:keyring(),now:()=>NOW});const b=bundle();importer.importBundle(b);assert.equal(importer.importBundle(b).rerun,true);assert.equal(f.db.prepare("SELECT count(*) n FROM customers").get().n,1);}finally{f.close()}});
test("changed source with same source id stops instead of overwriting",()=>{const f=fixture();try{const importer=createShadowImporter(f.db,{keyring:keyring(),now:()=>NOW});importer.importBundle(bundle());const changed=bundle({nonce:"b"});changed.microcms.customers[0].companyName="changed";assert.throws(()=>importer.importBundle(changed),/source content changed/);assert.equal(f.db.prepare("SELECT company_name FROM customers").get().company_name,"");}finally{f.close()}});
test("stale JSON relations are encrypted in quarantine",()=>{const f=fixture();try{const b=bundle({json:{"scheduled_post_retries.json":{missing:{retryCount:1,nextRetryAt:NOW}}}});const result=createShadowImporter(f.db,{keyring:keyring(),now:()=>NOW}).importBundle(b);assert.equal(result.quality.hasErrors,false);const row=f.db.prepare("SELECT reason,encrypted_payload FROM migration_quarantine").get();assert.equal(row.reason,"stale_retry");assert.ok(!row.encrypted_payload.includes("retryCount"));}finally{f.close()}});
test("imported exhausted legacy retry remains failed and cannot be claimed",()=>{const f=fixture();try{const b=bundle({microcms:{scheduled_posts:[{...sources().scheduled_posts[0],status:["failed"]}]},json:{"scheduled_post_retries.json":{p1:{retryCount:3,nextRetryAt:null}}}});createShadowImporter(f.db,{keyring:keyring(),now:()=>NOW}).importBundle(b);const row=f.db.prepare("SELECT state,attempt_count,next_attempt_at,last_error_code FROM scheduled_post_jobs WHERE scheduled_post_id='p1'").get();assert.deepEqual(row,{state:"failed",attempt_count:4,next_attempt_at:null,last_error_code:"legacy_retry_exhausted"});const repos=createRepositories(f.db,{now:()=>NOW});assert.equal(repos.jobs.claimNext({workerId:"worker",leaseExpiresAt:"2026-10-05T00:10:00.000Z",dueAt:NOW}),null);}finally{f.close()}});
test("verification compares IDs, dimensions and billing inputs",()=>{const f=fixture();try{const b=bundle();createShadowImporter(f.db,{keyring:keyring(),now:()=>NOW}).importBundle(b);const report=verifyShadow(f.db,b);assert.equal(report.allChecksPass,true);assert.equal(report.foreignKeyErrors,0);assert.equal(report.integrityCheck,"ok");}finally{f.close()}});
test("manifest detects altered export content",()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"manifest-"));try{const m={version:1,exportedAt:NOW,microcms:{},json:{}};for(const e of ["customers","post_schedules","schedule_texts","scheduled_posts","posting_logs"]){fs.writeFileSync(path.join(dir,e+".json"),"[]");m.microcms[e]={file:e+".json",count:0,idSetHash:contentHash([]),contentHash:contentHash([])}}m.manifestHash=sha256(JSON.stringify(m));fs.writeFileSync(path.join(dir,"manifest.json"),JSON.stringify(m));m.exportedAt="changed";fs.writeFileSync(path.join(dir,"manifest.json"),JSON.stringify(m));assert.throws(()=>loadExport(dir),/manifest checksum/);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
