const path = require("path");
require("dotenv").config({ path: path.join(__dirname, "..", ".env") });

const express = require("express");
const threadsRoutes = require("./routes/threads");
const xRoutes = require("./routes/x");
const facebookRoutes = require("./routes/facebook");
const instagramRoutes = require("./routes/instagram");
const linkedinRoutes = require("./routes/linkedin");
const authRoutes = require("./routes/auth");
const billingRoutes = require("./routes/billing");
const teamRoutes = require("./routes/team");
const snsConnectionsRoutes = require("./routes/snsConnections");
const accountRoutes = require("./routes/account");
const postsRoutes = require("./routes/posts");
const uploadsRoutes = require("./routes/uploads");
const aiRoutes = require("./routes/ai");
const schedulesRoutes = require("./routes/schedules");
const scheduleVideosRoutes = require("./routes/scheduleVideos");
const approvalsRoutes = require("./routes/approvals");
const invoicesRoutes = require("./routes/invoices");
const announcementsRoutes = require("./routes/announcements");
const adminStatsRoutes = require("./routes/adminStats");
const adminCustomersRoutes = require("./routes/adminCustomers");
const adminPostsRoutes = require("./routes/adminPosts");
const adminPasswordResetRoutes = require("./routes/adminPasswordReset");
const adminXSurchargeRoutes = require("./routes/adminXSurcharge");
const adminServerResourcesRoutes = require("./routes/adminServerResources");

const app = express();
app.use((req, res, next) => {
  res.setHeader("X-Robots-Tag", "noindex, nofollow");
  next();
});
app.use("/uploads", express.static(path.join(__dirname, "..", "uploads")));
app.use(threadsRoutes);
app.use(xRoutes);
app.use(facebookRoutes);
app.use(instagramRoutes);
app.use(linkedinRoutes);
app.use(authRoutes);
app.use(billingRoutes);
app.use(teamRoutes);
app.use(snsConnectionsRoutes);
app.use(accountRoutes);
app.use(postsRoutes);
app.use(uploadsRoutes);
app.use(aiRoutes);
app.use(schedulesRoutes);
app.use(scheduleVideosRoutes);
app.use(approvalsRoutes);
app.use(invoicesRoutes);
app.use(announcementsRoutes);
app.use(adminStatsRoutes);
app.use(adminCustomersRoutes);
app.use(adminPostsRoutes);
app.use(adminPasswordResetRoutes);
app.use(adminXSurchargeRoutes);
app.use(adminServerResourcesRoutes);

const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.info(`[sns-poster] listening on port ${port}`);
});
